# Permalinks
permalink:           pretty

# Setup
title:               Procédés des Systèmes Vivants
tagline:             Equipe *Génétique et Epigénétique des Champignons*
url:                 https://podo-gec.github.io

# About/contact
author:
  name:              Philippe Silar
  email:             philippe.silar@univ-paris-diderot.fr

