name: Bibliography

on: 
  push:
    paths: 'publications.md'

jobs:
  convert_via_pandoc:
    name: Convert via Pandoc
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: maxheld83/pandoc@v2
        with:
          args: "publications.md -o publications.docx"
